#!/usr/bin/env bash

if
  [[ -s "/home/alyosha/.rvm/gems/ruby-head@global/environment" ]]
then
  source "/home/alyosha/.rvm/gems/ruby-head@global/environment"
  exec gem "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/alyosha/.rvm/gems/ruby-head@global/environment'" >&2
  exit 1
fi
