#!/usr/bin/env bash

if
  [[ -s "/home/alyosha/.rvm/gems/ruby-head/environment" ]]
then
  source "/home/alyosha/.rvm/gems/ruby-head/environment"
  exec bundle "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/alyosha/.rvm/gems/ruby-head/environment'" >&2
  exit 1
fi
