# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1450270338);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1450270458);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1450269465);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1450270218);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1450269345);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1450270578);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 30);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.search.countryCode", "RU");
user_pref("browser.search.defaultenginename", "DuckDuckGo");
user_pref("browser.search.order.1", "Yahoo");
user_pref("browser.search.order.2", "Ixquick");
user_pref("browser.search.order.3", "Startpage");
user_pref("browser.search.order.4", "DuckDuckGo");
user_pref("browser.search.region", "RU");
user_pref("browser.search.selectedEngine", "Yahoo");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20151105184656");
user_pref("browser.startup.homepage", "http://www.linuxmint.com/start/rosa");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1450269859084");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1450269861134");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1450356261134");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1450183458014");
user_pref("datareporting.sessions.current.activeTicks", 5);
user_pref("datareporting.sessions.current.firstPaint", 1771);
user_pref("datareporting.sessions.current.main", 115);
user_pref("datareporting.sessions.current.sessionRestored", 2252);
user_pref("datareporting.sessions.current.startTime", "1450358438185");
user_pref("datareporting.sessions.current.totalTime", 28);
user_pref("datareporting.sessions.currentIndex", 4);
user_pref("datareporting.sessions.previous.2", "{\"s\":1450265624453,\"a\":10,\"t\":6910,\"c\":true,\"m\":125,\"fp\":2394,\"sr\":2424}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1450338408572,\"a\":8,\"t\":40,\"c\":true,\"m\":129,\"fp\":1629,\"sr\":2189}");
user_pref("datareporting.sessions.prunedIndex", 1);
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{\"langpack-ru@firefox.mozilla.org\":{\"version\":\"42.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-ru@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"42.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"42.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "mint-search-enhancer%40linuxmint.com:1.0,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:42.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1450270348);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20150902.02");
user_pref("extensions.lastAppVersion", "42.0");
user_pref("extensions.lastPlatformVersion", "42.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"langpack-ru@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-ru@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"42.0\",\"st\":1446750765000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"42.0\",\"st\":1446750735000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"42.0\",\"st\":1446750735000},\"mint-search-enhancer@linuxmint.com\":{\"d\":\"/usr/lib/firefox/browser/extensions/mint-search-enhancer@linuxmint.com\",\"e\":true,\"v\":\"1.0\",\"st\":1448795509000,\"mt\":1346324837000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"42.0\",\"st\":1448795328000,\"mt\":1446750202000}}}");
user_pref("gecko.buildID", "20151105184656");
user_pref("gecko.mstone", "42.0");
user_pref("idle.lastDailyNotification", 1450270777);
user_pref("keyword.URL", "https://duckduckgo.com/?t=lm&q=");
user_pref("media.gmp-gmpopenh264.abi", "x86-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1450183524);
user_pref("media.gmp-gmpopenh264.version", "1.5.1");
user_pref("media.gmp-manager.buildID", "20151105184656");
user_pref("media.gmp-manager.lastCheck", 1450183521);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("network.protocol-handler.app.apt", "/usr/bin/apturl");
user_pref("network.protocol-handler.app.apt+http", "/usr/bin/apturl");
user_pref("network.protocol-handler.warn-external.apt", true);
user_pref("network.protocol-handler.warn-external.apt+http", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1450184100);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1450184100);
user_pref("toolkit.startup.last_success", 1450358438);
user_pref("toolkit.telemetry.cachedClientID", "4c54ffec-7104-460e-9403-e54bcfc782d9");
user_pref("toolkit.telemetry.previousBuildID", "20151105184656");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
